# A list of databases to connect to
database:
  host: localhost
  port: 7654
  user: lifelife
  password: lifelife
  database: lifelife

# Which tables to listen for and how to report on changes
listen:
  general_properties_change:
    table: properties
    payload:
      id: id
      human_id: human_id

  property_change_via_images:
    table: property_images
    payload:
      id: property_id

  property_change_via_events:
    table: property_events
    payload:
      id: property_id
